devices([
  "iPhone 17 Pro",
  "iPhone 17 Pro Max"
])

languages([
  "en-US"
])

scheme("AppUITests")
workspace("App.xcworkspace")

output_directory("./fastlane/screenshots")

clear_previous_screenshots(true)
