devices([
  "iPhone 16 Pro Max",
  "iPhone 16 Pro",
  "iPhone SE (3rd generation)",
  "iPad Pro 13-inch (M4)"
])

languages([
  "en-US"
])

scheme("AppUITests")
workspace("App.xcworkspace")

output_directory("./fastlane/screenshots")

clear_previous_screenshots(true)

override_status_bar(true)
