devices([
  "iPhone 17 Pro Max",
  "iPad Pro 13-inch (M5)"
])

languages([
  "en-US"
])

scheme("AppUITests")
workspace("App.xcworkspace")

output_directory("./fastlane/screenshots")

clear_previous_screenshots(true)
