platform :ios, '16.0'
use_frameworks!

install! 'cocoapods', :disable_input_output_paths => true

target 'App' do
  # Use Capacitor from CocoaPods trunk (remote, no node_modules needed)
  pod 'Capacitor', '~> 8.0'
  pod 'CapacitorCordova', '~> 8.0'
  pod 'CapacitorApp', '~> 8.0'
  pod 'CapacitorLocalNotifications', '~> 8.0'
  pod 'CapacitorPushNotifications', '~> 8.0'
  pod 'CapacitorSplashScreen', '~> 8.0'
  pod 'CapacitorStatusBar', '~> 8.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end
